[project]
name = "simulator"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.10.1",
    "gymnasium>=1.2.1",
    "numpy>=2.3.3",
    "pygame>=2.6.1",
    "stable-baselines3[extra]>=2.7.0",
    "timm>=1.0.20",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
